"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { API_BASE_URL } from "@/lib/api";

export default function Home() {
  const [apiStatus, setApiStatus] = useState<string>("checking");

  useEffect(() => {
    const checkAPI = async () => {
      try {
        const response = await fetch(`${API_BASE_URL}/`);
        if (response.ok) {
          setApiStatus("connected");
        } else {
          setApiStatus("error");
        }
      } catch (error) {
        setApiStatus("disconnected");
      }
    };
    checkAPI();
  }, []);

  return (
    <div className="max-w-6xl mx-auto">
      {/* Hero Section */}
      <div className="bg-gradient-to-r from-primary to-primary-dark text-white rounded-2xl p-12 shadow-xl mb-8">
        <h1 className="text-5xl font-bold mb-4">
          📊 Investment Portfolio Monitoring Agent
        </h1>
        <p className="text-xl text-white/90">
          AI-powered multi-agent system for real-time portfolio analysis, risk monitoring, and intelligent forecasting
        </p>
        <div className="mt-6 flex items-center gap-4">
          <Link
            href="/portfolio"
            className="bg-white text-primary px-8 py-3 rounded-lg font-semibold hover:bg-gray-100 transition-colors"
          >
            Get Started →
          </Link>
          <div className="flex items-center gap-2">
            <div className={`w-3 h-3 rounded-full ${
              apiStatus === "connected" ? "bg-green-400" : 
              apiStatus === "disconnected" ? "bg-red-400" : 
              "bg-yellow-400 animate-pulse"
            }`} />
            <span className="text-white/80 text-sm">
              {apiStatus === "connected" ? "API Connected" : 
               apiStatus === "disconnected" ? "API Disconnected" : 
               "Checking API..."}
            </span>
          </div>
        </div>
      </div>

      {/* Features Grid */}
      <div className="grid md:grid-cols-3 gap-6 mb-8">
        <FeatureCard
          icon="📈"
          title="Portfolio Dashboard"
          description="Visual analytics with interactive charts showing portfolio value, allocation, and drift"
          href="/dashboard"
        />
        <FeatureCard
          icon="⚠️"
          title="Risk Analysis"
          description="Comprehensive risk metrics including volatility, Sharpe ratio, and maximum drawdown"
          href="/risk"
        />
        <FeatureCard
          icon="🚨"
          title="Smart Alerts"
          description="Two-stage anomaly detection with AI-powered news attribution and citations"
          href="/alerts"
        />
        <FeatureCard
          icon="🤖"
          title="ML Forecast"
          description="5-day volatility predictions using ensemble models (GARCH, XGBoost, Random Forest)"
          href="/forecast"
        />
        <FeatureCard
          icon="🔍"
          title="Agent Trace"
          description="Transparent view into multi-agent execution with tool calls and reasoning steps"
          href="/trace"
        />
        <FeatureCard
          icon="📄"
          title="Investment Briefing"
          description="Mandate-conditioned reports generated by AI without trading directives"
          href="/alerts"
        />
      </div>

      {/* Info Section */}
      <div className="bg-blue-50 border-l-4 border-blue-500 p-6 rounded-lg">
        <h3 className="text-lg font-semibold text-blue-900 mb-2">
          💡 About This System
        </h3>
        <p className="text-blue-800">
          This is a <strong>monitoring and explanation system</strong>, not a trading system. 
          It monitors portfolio risk, detects anomalies, explains events with news citations, 
          and forecasts volatility using ML — but <strong>never</strong> places orders or issues buy/sell directives.
        </p>
      </div>
    </div>
  );
}

function FeatureCard({
  icon,
  title,
  description,
  href,
}: {
  icon: string;
  title: string;
  description: string;
  href: string;
}) {
  return (
    <Link href={href} className="block">
      <div className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-shadow border border-gray-100 h-full">
        <div className="text-4xl mb-3">{icon}</div>
        <h3 className="text-xl font-semibold text-gray-900 mb-2">{title}</h3>
        <p className="text-gray-600">{description}</p>
      </div>
    </Link>
  );
}
