"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { getAlerts, getRiskMetrics, AlertItem } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { TableSkeleton } from "@/components/ui/Skeleton";

export default function AlertsPage() {
  const [loading, setLoading] = useState(true);
  const [alerts, setAlerts] = useState<AlertItem[]>([]);
  const [briefing, setBriefing] = useState<string>("");
  const [filter, setFilter] = useState<string>("ALL");

  useEffect(() => {
    let mounted = true;
    const fetchAlerts = async () => {
      try {
        setLoading(true);
        const [alertsData, riskData] = await Promise.allSettled([
          getAlerts(),
          getRiskMetrics(),
        ]);

        if (mounted) {
          if (alertsData.status === "fulfilled") setAlerts(alertsData.value);
          if (riskData.status === "fulfilled" && riskData.value?.briefing) {
            setBriefing(riskData.value.briefing);
          }
        }
      } catch (err) {
        // quiet fallback
      } finally {
        if (mounted) setLoading(false);
      }
    };
    fetchAlerts();
    return () => {
      mounted = false;
    };
  }, []);

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="h-8 w-64 bg-slate-200 animate-pulse rounded-md" />
        <TableSkeleton rows={4} />
      </div>
    );
  }

  const filteredAlerts = alerts.filter((a) => {
    if (filter === "ALL") return true;
    return a.severity === filter;
  });

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold text-slate-900 tracking-tight">
            Market Alerts & Material Events
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            Two-stage anomaly detection with deterministic triggers and verified news citations.
          </p>
        </div>

        {/* Severity Filter Pills */}
        <div className="flex items-center gap-1.5 bg-white border border-slate-200 p-1 rounded-lg shadow-xs text-xs">
          {["ALL", "CRITICAL", "WARNING"].map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-3 py-1 rounded-md font-semibold transition-all ${
                filter === f
                  ? "bg-slate-900 text-white shadow-xs"
                  : "text-slate-600 hover:text-slate-900 hover:bg-slate-50"
              }`}
            >
              {f}
            </button>
          ))}
        </div>
      </div>

      {/* Executive Briefing Memo (Morningstar Style) */}
      {briefing && (
        <Card className="border-l-4 border-l-slate-900">
          <CardHeader>
            <CardTitle>Portfolio Executive Briefing</CardTitle>
            <Badge variant="neutral">Morningstar Format</Badge>
          </CardHeader>
          <CardContent className="p-6 text-sm text-slate-700 leading-relaxed space-y-3 font-serif">
            <div className="whitespace-pre-line font-sans text-xs sm:text-sm bg-slate-50/50 p-4 rounded-lg border border-slate-100">
              {briefing}
            </div>
            <p className="text-[11px] text-slate-400 font-sans italic pt-2">
              Generated by Investment Monitoring Engine conditioned on risk-free rate and mandate parameters.
            </p>
          </CardContent>
        </Card>
      )}

      {/* Alerts Feed */}
      {filteredAlerts.length === 0 ? (
        <EmptyState
          title="No Active Material Event Alerts"
          description="All portfolio positions are operating within normal parametric boundaries (z-scores < 2.0σ and contained drawdown)."
          actionText="Execute Analysis Check"
          actionHref="/portfolio"
        />
      ) : (
        <div className="space-y-4">
          {filteredAlerts.map((alert) => (
            <Card key={alert.id} className="hover:border-slate-300 transition-colors">
              <CardContent className="p-5">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-100">
                  <div className="flex items-center gap-2.5">
                    <span
                      className={`text-[10px] font-bold px-2 py-0.5 rounded border uppercase tracking-wider ${
                        alert.severity === "CRITICAL"
                          ? "bg-rose-50 text-rose-700 border-rose-200"
                          : alert.severity === "WARNING"
                          ? "bg-amber-50 text-amber-700 border-amber-200"
                          : "bg-slate-100 text-slate-700 border-slate-200"
                      }`}
                    >
                      {alert.severity}
                    </span>
                    <span className="font-bold text-slate-900 font-mono text-sm">
                      {alert.ticker}
                    </span>
                    <span className="text-slate-300">•</span>
                    <span className="text-xs font-semibold text-slate-700">
                      {alert.title}
                    </span>
                  </div>

                  <div className="flex items-center gap-3 text-xs font-mono text-slate-500">
                    {alert.return_value !== null && alert.return_value !== undefined && (
                      <span
                        className={
                          alert.return_value >= 0 ? "text-emerald-600 font-bold" : "text-rose-600 font-bold"
                        }
                      >
                        Return: {(alert.return_value * 100).toFixed(2)}%
                      </span>
                    )}
                    {alert.z_score !== null && alert.z_score !== undefined && (
                      <span className="bg-slate-100 px-2 py-0.5 rounded text-slate-700 font-bold">
                        {alert.z_score.toFixed(1)}σ
                      </span>
                    )}
                  </div>
                </div>

                {/* Description */}
                <p className="mt-3 text-xs text-slate-600 leading-relaxed">
                  {alert.description}
                </p>

                {/* Trigger Reason Box */}
                <div className="mt-3 bg-slate-50 px-3 py-2 rounded-lg text-[11px] text-slate-500 font-mono border border-slate-100 flex items-center justify-between">
                  <span>Trigger Condition: {alert.trigger_reason}</span>
                  <span>{new Date(alert.timestamp).toLocaleDateString()}</span>
                </div>

                {/* Citations List */}
                {alert.citations && alert.citations.length > 0 && (
                  <div className="mt-3 pt-3 border-t border-slate-100 space-y-1.5">
                    <span className="text-[10px] font-semibold text-slate-400 uppercase tracking-wider block">
                      Attributed News Evidence:
                    </span>
                    {alert.citations.map((c, idx) => (
                      <div key={idx} className="text-xs text-slate-600 flex items-center gap-2">
                        <span className="text-blue-500">↗</span>
                        {c.url ? (
                          <a
                            href={c.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-blue-600 hover:underline font-medium"
                          >
                            {c.title || c.url}
                          </a>
                        ) : (
                          <span>{c.title}</span>
                        )}
                        {c.source && (
                          <span className="text-[10px] text-slate-400">({c.source})</span>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
